apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- github.com/thomasstxyz/example-kustomize-base/base
components:
  - app-version
namePrefix: prod-
patchesStrategicMerge:
  - "settings/deployment.yaml"
patches:
- target:
    kind: Deployment
    name: podinfo
  patch: |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: podinfo
    spec:
      template:
        spec:
          containers:
          - name: podinfod
            env:
            - name: PODINFO_UI_COLOR
              value: "#d7e70c"
